openapi: 3.0.3
info:
  title: Schema del Progetto Volontari
  version: 202312.06.00
  x-summary: Schema del progetto volontari compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    Lavoro di pubblica utilità o progetti di utilità sociale.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    PolizzaVolontari:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-volontari/latest/polizza-volontari.oas3.yaml#/components/schemas/PolizzaVolontari"

    ProgettoVolontariInail:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_volunteers/ProgettoVolontariINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_volunteers/"
        nome_progetto: nomeProgetto
        data_inizio_progetto: dataInizioProgetto
        data_fine_progetto: dataFineProgetto
        numero_delibera_progetto: numeroDeliberaProgetto
        data_delibera_progetto: dataDeliberaProgetto
        progressivo_progetto: progressivoProgetto
        progetto_relativo_a_polizza:
          "@id": progettoRelativoAPolizza
      additionalProperties: true
      description:
          Questo schema rappresenta un progetto di pubblica utilità ed è associato ad https://w3id.org/italia/work-accident/onto/proc17_volunteers/ProgettoVolontariINAIL.
      required:
        - nome_progetto
        - data_inizio_progetto
        - data_fine_progetto
        - numero_delibera_progetto
        - data_delibera_progetto
        - progressivo_progetto
      properties:
        nome_progetto:
          type: string
          maxLength: 400
        data_inizio_progetto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_progetto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        numero_delibera_progetto:
          type: integer
          format: int64
        data_delibera_progetto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        progressivo_progetto:
          type: integer
          format: int64
        progetto_relativo_a_polizza:
          type: object
          items:
            $ref: "#/components/schemas/PolizzaVolontari"
      example:
        nome_progetto: "Race to Green World - Roma"
        data_inizio_progetto: '2015-05-06'
        data_fine_progetto: '2015-06-06'
        numero_delibera_progetto: 1274943
        data_delibera_progetto: '2015-05-01'
        progressivo_progetto: 005
        volontario_relativo_a_polizza:
           $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-volontari/latest/polizza-volontari.oas3.yaml#/components/schemas/PolizzaVolontari/example"