openapi: 3.0.3
info:
  title: Schema dell'Apparecchio RX
  version: 202312.14.00
  x-summary: Schema dell'apparecchio rx compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    Ai fini assicurativi per apparecchio radiologico, che costituisce l’elemento di individuazione e di determinazione del premio, si intende il complesso generatore di alta tensione composto da: tavoli di comando per alimentazione, cavi schermati di collegamento fra tavoli di comando e tubi radiogeni e, infine, uno o più tubi radiogeni montati su accessori d’esame (ortoscopi, trocoscopi, stratigrafi, ecc.).

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    PolizzaApparecchiRx:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-apparecchi-rx/latest/polizza-apparecchi-rx.oas3.yaml#/components/schemas/PolizzaApparecchiRx"

    MatricolaApparecchio:
      type: string
      maxLength: 50
      x-refersTo: https://w3id.org/italia/work-accident/onto/proc17_xray_machine/matricolaApparecchio
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/work-accident/onto/proc17_xray_machine/matricolaApparecchio.
      example: 'as234543'

    ApparecchioRxInail:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_xray_machine/ApparecchioRXINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_xray_machine/"
        tipologia_apparecchio: tipologiaApparecchio
        apparecchio_relativo_a_polizza:
          "@id": apparecchioRelativoAPolizza
      additionalProperties: true
      description:
          Questo schema rappresenta un apparecchio rx ed è associato ad https://w3id.org/italia/work-accident/onto/proc17_xray_machine/ApparecchioRXINAIL.
      required:
        - matricola_apparecchio
        - tipologia_apparecchio
      properties:
        matricola_apparecchio:
          $ref: "#/components/schemas/MatricolaApparecchio"
        tipologia_apparecchio:
          type: string
          maxLength: 100
        apparecchio_relativo_a_polizza:
          type: object
          items:
            $ref: "#/components/schemas/PolizzaApparecchiRx"
      example:
        matricola_apparecchio:
          $ref: "#/components/schemas/MatricolaApparecchio/example"
        tipologia_apparecchio: 'A3 - Installati presso studi privati di radiologia'
        apparecchio_relativo_a_polizza:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-apparecchi-rx/latest/polizza-apparecchi-rx.oas3.yaml#/components/schemas/PolizzaApparecchiRx/example"