openapi: 3.0.3
info:
  title: Schema della Denuncia Iscrizione Sostanze Radioattive
  version: 202312.18.00
  x-summary: Schema della denuncia di iscrizione delle sostanze radioattive combatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    Denuncia di iscrizione di una nuova ditta con contestuale apertura di una polizza assicurativa per soggetti esposti a sostanze radioattive.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    SedeInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail"
    SoggettoAssicurante:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/soggetto-assicurante/latest/soggetto-assicurante.oas3.yaml#/components/schemas/SoggettoAssicurante"
    PolizzaSostanzeRadioattive:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-sostanze-radioattive/latest/polizza-sostanze-radioattive.oas3.yaml#/components/schemas/PolizzaSostanzeRadioattive"

    NumeroPraticaDenunciaIscrizione:
      type: number
      format: double
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/numeroPraticaDenuncia
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/work-accident/onto/core/numeroPraticaDenuncia.
      example: 14758

    DenunciaIscrizioneSostanzeRadioattive:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_radioactive_substances/DenunciaDiIscrizioneSostanzeRadioattiveINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_radioactive_substances/"
        anno_competenza_sostanze_radioattive: annoCompetenzaSostanzeRadioattive
      additionalProperties: true
      description:
         Questo schema rappresenta la denuncia di iscrizione delle sostanze radioattive ed è associato a https://w3id.org/italia/work-accident/onto/proc17_radioactive_substances/DenunciaDiIscrizioneSostanzeRadioattiveINAIL.
      required:
      - numero_pratica_denuncia_iscrizione
      - data_denuncia_iscrizione
      - data_protocollazione_denuncia_iscrizione
      - codice_esito_pratica
      - descrizione_esito_pratica
      - tipo_denuncia
      - anno_competenza_sostanze_radioattive
      properties:
        numero_pratica_denuncia_iscrizione:
          $ref: "#/components/schemas/NumeroPraticaDenunciaIscrizione"
        data_denuncia_iscrizione:
          $ref: "#/components/schemas/DataDenunciaIscrizione"
        data_protocollazione_denuncia_iscrizione:
          $ref: "#/components/schemas/DataProtocollazioneDenunciaIscrizione"
        codice_esito_pratica:
          $ref: "#/components/schemas/CodiceEsitoPratica"
        descrizione_esito_pratica:
          $ref: "#/components/schemas/DescrizioneEsitoPratica"
        tipo_denuncia:
          $ref: "#/components/schemas/TipoDenuncia"
        anno_competenza_sostanze_radioattive:
          type: string
          maxLength: 10
        relativa_a_soggetto:
          $ref: "#/components/schemas/RelativaSoggetto"
        relativa_a_sede_inail:
          $ref: "#/components/schemas/RelativaSedeInail"
        relativa_a_polizza:
          $ref: "#/components/schemas/RelativaPolizza"
      example:
        numero_pratica_denuncia_iscrizione:
          $ref: "#/components/schemas/NumeroPraticaDenunciaIscrizione/example"
        data_denuncia_iscrizione:
          $ref: "#/components/schemas/DataDenunciaIscrizione/example"
        data_protocollazione_denuncia_iscrizione:
          $ref: "#/components/schemas/DataProtocollazioneDenunciaIscrizione/example"
        codice_esito_pratica:
          $ref: "#/components/schemas/CodiceEsitoPratica/example"
        descrizione_esito_pratica:
          $ref: "#/components/schemas/DescrizioneEsitoPratica/example"
        tipo_denuncia:
          $ref: "#/components/schemas/TipoDenuncia/example"
        anno_competenza_sostanze_radioattive: '20'
        relativa_a_soggetto:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/soggetto-assicurante/latest/soggetto-assicurante.oas3.yaml#/components/schemas/SoggettoAssicurante/example"
        relativa_a_sede_inail:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail/example"
        relativa_a_polizza:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-sostanze-radioattive/latest/polizza-sostanze-radioattive.oas3.yaml#/components/schemas/PolizzaSostanzeRadioattive/example"

    DataDenunciaIscrizione:
      type: string
      format: date
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/dataDenuncia
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example: '2008-07-03'
    DataProtocollazioneDenunciaIscrizione:
      type: string
      format: date
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/dataProtocollazioneDenuncia
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example: '2008-07-05'
    CodiceEsitoPratica:
      type: string
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/codiceEsitoPratica
      maxLength: 10
      example: 'C'
    DescrizioneEsitoPratica:
      type: string
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/descrizioneEsitoPratica
      maxLength: 250
      example: 'Confermata'
    TipoDenuncia:
      type: string
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/tipoDiDenuncia
      maxLength: 200
      example: 'DENUNCIA ISCRIZIONE'

    RelativaSoggetto:
      type: object
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/denunciaRelativaASoggettoAssicurante
      items:
        $ref: "#/components/schemas/SoggettoAssicurante"
    RelativaSedeInail:
      type: object
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/denunciaRelativaASedeINAIL
      items:
        $ref: "#/components/schemas/SedeInail"
    RelativaPolizza:
      type: object
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/denunciaRelativaAPolizza
      items:
        $ref: "#/components/schemas/PolizzaSostanzeRadioattive"