openapi: 3.0.3
info:
  title: Schema del Soggetto Esposto Apparecchi RX
  version: 202312.14.00
  x-summary: Schema del soggetto esposto ad apparecchi rx compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    I soggetti esposti sono persone fisiche che sono addette all’utilizzo degli apparecchi RX e quindi esposti in maniera prolungata alle onde elettromagnetiche dell’apparecchio.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    ApparecchioRxInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/apparecchio-rx/latest/apparecchio-rx.oas3.yaml#/components/schemas/ApparecchioRxInail"

    SoggettoEspostoAdApparecchioInail:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_xray_machines/SoggettoEspostoAApparecchioINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_xray_machines/"
        soggetto_esposto_ad_apparecchio:
          "@id": soggettoEspostoAdApparecchio
      additionalProperties: true
      description:
          Questo schema rappresenta un soggetto esposto ad un apparecchio rx ed è associato ad https://w3id.org/italia/work-accident/onto/proc17_xray_machines/SoggettoEspostoAApparecchioINAIL.
      properties:
        numero_giornate_soggetto_assicurato:
          $ref: "#/components/schemas/NumeroGiornateSoggettoAssicurato"
        data_inizio_rischio:
          $ref: "#/components/schemas/DataInizioRischio"
        soggetto_esposto_ad_apparecchio:
          type: object
          items:
            $ref: "#/components/schemas/ApparecchioRxInail"
      example:
        numero_giornate_soggetto_assicurato:
          $ref: "#/components/schemas/NumeroGiornateSoggettoAssicurato/example"
        data_inizio_rischio:
          $ref: '#/components/schemas/DataInizioRischio/example'
        soggetto_esposto_ad_apparecchio:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/apparecchio-rx/latest/apparecchio-rx.oas3.yaml#/components/schemas/ApparecchioRx/example"

    NumeroGiornateSoggettoAssicurato:
        type: integer
        format: int32
        x-refersTo: https://w3id.org/italia/work-accident/onto/core/numeroGiornateSoggettoAssicurato
        example: 15
    DataInizioRischio:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
          x-refersTo: https://w3id.org/italia/work-accident/onto/core/dataInizioRischio
          example: '2017-03-06'