openapi: 3.0.3
info:
  title: Schema della Denuncia Variazione Apparecchi RX
  version: 202312.13.00
  x-summary: Schema della denuncia di variazione apparecchi rx compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    Denuncia che consente ai soggetti assicuranti l'apertura di una o più polizze assicurative per soggetti esposti ad apparecchi RX su una PAT già attiva e l'attivazione di una nuova PAT con contestuale apertura di una o più polizze assicurative contro apparecchi RX sul codice ditta attivo.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    ApparecchioRxInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/apparecchio-rx/latest/apparecchio-rx.oas3.yaml#/components/schemas/ApparecchioRxInail"
    SoggettoEspostoAdApparecchioInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/soggetto-esposto-rx/latest/soggetto-esposto-rx.oas3.yaml#/components/schemas/SoggettoEspostoAdApparecchioInail"
    SedeInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail"
    SoggettoAssicurante:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/soggetto-assicurante/latest/soggetto-assicurante.oas3.yaml#/components/schemas/SoggettoAssicurante"
    PolizzaApparecchiRx:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-apparecchi-rx/latest/polizza-apparecchi-rx.oas3.yaml#/components/schemas/PolizzaApparecchiRx"

    NumeroPraticaDenunciaVariazione:
      type: number
      format: double
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/numeroPraticaDenuncia
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/work-accident/onto/core/numeroPraticaDenuncia.
      example: 18475

    DenunciaVariazioneApparecchiRx:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_xray_machine/DenunciaDiVariazionePolizzaApparecchiRXINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_xray_machine/"
        data_inizio_validita_apparecchio: dataInizioValiditaApparecchio
        data_fine_validita_apparecchio: dataFineValiditaApparecchio
        data_inizio_validita_soggetto_esposto: dataInizioValiditaSoggettoEsposto
        data_fine_validita_soggetto_esposto: dataFineValiditaSoggettoEsposto
        tipologia_dettaglio: tipologiaDettaglio
        denuncia_apparecchi_rx_relativa_apparecchio:
          "@id": denunciaApparecchiRXRelativaA
        denuncia_apparecchi_rx_relativa_soggetto:
          "@id": denunciaApparecchiRXRelativaA
        #relativa_a_soggetto:
        #  "@id": denunciaRelativaASoggettoAssicurante
        #relativa_a_sede_inail:
        #  "@id": denunciaRelativaASedeINAIL
      additionalProperties: true
      description:
         Questo schema rappresenta la denuncia di variazione apparecchi rx ed è associato a DenunciaDiVariazionePolizzaApparecchiRXINAIL.
      required:
      - numero_pratica_denuncia_variazione
      - data_denuncia_variazione
      - data_protocollazione_denuncia_variazione
      - codice_esito_pratica
      - descrizione_esito_pratica
      - tipo_denuncia
      - data_inizio_validita_apparecchio
      - data_fine_validita_apparecchio
      - data_inizio_validita_soggetto_esposto
      - data_fine_validita_soggetto_esposto
      - tipologia_dettaglio
      properties:
        numero_pratica_denuncia_variazione:
          $ref: "#/components/schemas/NumeroPraticaDenunciaVariazione"
        data_denuncia_variazione:
          $ref: "#/components/schemas/DataDenunciaVariazione"
        data_protocollazione_denuncia_variazione:
          $ref: "#/components/schemas/DataProtocollazioneDenunciaVariazione"
        codice_esito_pratica:
          $ref: "#/components/schemas/CodiceEsitoPratica"
        descrizione_esito_pratica:
          $ref: "#/components/schemas/DescrizioneEsitoPratica"
        tipo_denuncia:
          $ref: "#/components/schemas/TipoDenuncia"
        data_inizio_validita_apparecchio:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_validita_apparecchio:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_validita_soggetto_esposto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_validita_soggetto_esposto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        tipologia_dettaglio:
          type: string
          maxLength: 50
        denuncia_apparecchi_rx_relativa_apparecchio:
          type: object
          items:
            $ref: "#/components/schemas/ApparecchioRxInail"
        denuncia_apparecchi_rx_relativa_soggetto:
          type: object
          items:
            $ref: "#/components/schemas/SoggettoEspostoAdApparecchioInail"
        relativa_a_soggetto:
          $ref: "#/components/schemas/RelativaSoggetto"
        relativa_a_sede_inail:
          $ref: "#/components/schemas/RelativaSedeInail"
        relativa_a_polizza:
          $ref: "#/components/schemas/RelativaPolizza"
        #relativa_a_soggetto:
        #  type: object
        #  items:
        #    $ref: "#/components/schemas/SoggettoAssicurante"
        #relativa_a_sede_inail:
        #  type: object
        #  items:
        #    $ref: "#/components/schemas/SedeInail"
      example:
        numero_pratica_denuncia_variazione:
          $ref: "#/components/schemas/NumeroPraticaDenunciaVariazione/example"
        data_denuncia_variazione:
          $ref: "#/components/schemas/DataDenunciaVariazione/example"
        data_protocollazione_denuncia_variazione:
          $ref: "#/components/schemas/DataProtocollazioneDenunciaVariazione/example"
        codice_esito_pratica:
          $ref: "#/components/schemas/CodiceEsitoPratica/example"
        descrizione_esito_pratica:
          $ref: "#/components/schemas/DescrizioneEsitoPratica/example"
        tipo_denuncia:
          $ref: "#/components/schemas/TipoDenuncia/example"
        data_inizio_validita_apparecchio: '2020-06-28'
        data_fine_validita_apparecchio: '2020-11-28'
        data_inizio_validita_soggetto_esposto: '2020-06-28'
        data_fine_validita_soggetto_esposto: '2020-09-28'
        tipologia_dettaglio: "Soggetto Esposto"
        denuncia_apparecchi_rx_relativa_apparecchio:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/apparecchio-rx/latest/apparecchio-rx.oas3.yaml#/components/schemas/ApparecchioRx/example"
        denuncia_apparecchi_rx_relativa_soggetto:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/soggetto-esposto-rx/latest/soggetto-esposto-rx.oas3.yaml#/components/schemas/SoggettoEspostoAdApparecchioInail/example"
        relativa_a_soggetto:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/soggetto-assicurante/latest/soggetto-assicurante.oas3.yaml#/components/schemas/SoggettoAssicurante/example"
        relativa_a_sede_inail:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail/example"
        relativa_a_polizza:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-apparecchi-rx/latest/polizza-apparecchi-rx.oas3.yaml#/components/schemas/PolizzaApparecchiRx/example"

    DataDenunciaVariazione:
      type: string
      format: date
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/dataDenuncia
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example: '2020-06-18'
    DataProtocollazioneDenunciaVariazione:
      type: string
      format: date
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/dataProtocollazioneDenuncia
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example: '2020-06-20'
    CodiceEsitoPratica:
      type: string
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/codiceEsitoPratica
      maxLength: 10
      example: 'C'
    DescrizioneEsitoPratica:
      type: string
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/descrizioneEsitoPratica
      maxLength: 250
      example: 'Confermata'
    TipoDenuncia:
      type: string
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/tipoDiDenuncia
      maxLength: 200
      example: 'DENUNCIA VARIAZIONE'

    RelativaSoggetto:
      type: object
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/denunciaRelativaASoggettoAssicurante
      items:
        $ref: "#/components/schemas/SoggettoAssicurante"
    RelativaSedeInail:
      type: object
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/denunciaRelativaASedeINAIL
      items:
        $ref: "#/components/schemas/SedeInail"
    RelativaPolizza:
      type: object
      x-refersTo: https://w3id.org/italia/work-accident/onto/core/denunciaRelativaAPolizza
      items:
        $ref: "#/components/schemas/PolizzaApparecchiRx"