openapi: 3.0.3
info:
  title: Schema dell'equipaggio di una nave
  version: 202312.14.00
  x-summary: Schema dell'equipaggio di una nave compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    L'equipaggio di una nave comprende tutto il personale imbarcato a bordo di una nave ed include qualsiasi persona assunta  direttamente,  sia  da un armatore sia tramite un'agenzia di armamento,  il  cui  luogo  di lavoro abituale e' a bordo della nave, compreso  il  comandante, gli ufficiali, i membri dell'equipaggio, ed il personale addetto al catering, e ai servizi di sala e alberghieri.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    Equipaggio:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_seafarer/EquipaggioNave
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_seafarer/"
        qualifica_soggetto_assicurato: qualificaSoggettoAssicurato
        equipaggio_costituito_da:
          "@id": equipaggioCostituitoDaMembro
      additionalProperties: true
      description:
          Questo schema rappresenta l'equipaggio di una nave ed è associato ad https://w3id.org/italia/work-accident/onto/proc17_seafarer/EquipaggioNave.
      required:
         - qualifica_soggetto_assicurato
      properties:
        qualifica_soggetto_assicurato:
          type: string
          maxLength: 150
        equipaggio_costituito_da:
          type: object
          items:
            $ref: "#/components/schemas/MembroEquipaggio"
      example:
        qualifica_soggetto_assicurato: 'sottoufficiali e comuni'
        equipaggio_costituito_da:
          grado_membro_equipaggio:
            $ref: "#/components/schemas/MembroEquipaggio/example"

    MembroEquipaggio:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_seafarer/MembroEquipaggioNave
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_seafarer/"
        grado_membro_equipaggio: gradoMembroEquipaggio
        equipaggio_costituito_da:
          "@id": equipaggioCostituitoDaMembro
      additionalProperties: true
      description:
          Questo schema rappresenta il membro dell'equipaggio di una nave ed è associato ad https://w3id.org/italia/work-accident/onto/proc17_seafarer/MembroEquipaggioNave.
      required:
         - grado_membro_equipaggio
      properties:
        grado_membro_equipaggio:
          type: string
          maxLength: 150
      example:
        grado_membro_equipaggio: 'sottoufficale'