openapi: 3.0.3
info:
  title: Schema della Sostanza Radioattiva
  version: 202312.18.00
  x-summary: Schema della sostanza radioattiva compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
    Una sostanza radioattiva è una sostanza che presenti il fenomeno della radioattività cioè di disintegrazione spontanea di un nuclide, con emissione di una particella o di un fotone o di entrambi, che comporti la formazione di un nuovo nuclide.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    PolizzaSostanzeRadioattive:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-sostanze-radioattive/latest/polizza-sostanze-radioattive.oas3.yaml#/components/schemas/PolizzaSostanzeRadioattive"

    SostanzaRadioattiva:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc17_radioactive_substances/SostanzaRadioattivaINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc17_radioactive_substances/"
        gruppo_sostanze_radioattive: gruppoSostanzeRadioattive
        sorgente_sostanza_radioattiva: sorgenteSostanzaRadioattiva
        tipo_sostanza_radioattiva: tipoSostanzaRadioattiva
        numero_megabecquerel: numeroMegabecquerel
        sostanza_radioattiva_relativa_a_polizza:
          "@id": SostanzaRadioattivaRelativaAPolizza
      additionalProperties: true
      description:
          Questo schema rappresenta una sostanza radioattiva ed è associato ad https://w3id.org/italia/work-accident/onto/proc17_radioactive_substances/SostanzaRadioattivaINAIL.
      required:
        - gruppo_sostanze_radioattive
        - sorgente_sostanza_radioattiva
        - tipo_sostanza_radioattiva
        - numero_megabecquerel
      properties:
        gruppo_sostanze_radioattive:
          type: string
          maxLength: 100
        sorgente_sostanza_radioattiva:
          type: string
          maxLength: 100
        tipo_sostanza_radioattiva:
          type: string
          maxLength: 50
        numero_megabecquerel:
          type: number
          format: double
        sostanza_radioattiva_relativa_a_polizza:
          type: object
          items:
            $ref: "#/components/schemas/PolizzaSostanzeRadioattive"
      example:
        gruppo_sostanze_radioattive: 'Gruppo II - nuclidi di radiotossicità elevata'
        sorgente_sostanza_radioattiva: 'Sorgenti sigillate'
        tipo_sostanza_radioattiva: 'Iodio125'
        numero_megabecquerel: 3292
        sostanza_radioattiva_relativa_a_polizza:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/polizza-sostanze-radioattive/latest/polizza-sostanze-radioattive.oas3.yaml#/components/schemas/PolizzaSostanzeRadioattive/example"